server:
  port: 8080
 
spring:    
  rabbitmq:
    host: localhost
    port: 5672
    
management:
  security:
    enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
  