server:
  port:
    8443
  ssl:
    enabled: true
    keyStoreType: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password
    key-alias: tomcat
  http:
    port:
      8081



#mysql database setting
#spring.profiles.active=dev
spring.jpa.database: mysql
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost/oauth?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: oauth
spring.datasource.password: oauth
# db init settings
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.showSql: true
spring.datasource.initialization-mode: NEVER
spring.datasource.sqlScriptEncoding: UTF-8


#connection pool settings
spring.datasource.dbcp2.initial-size: 10
spring.datasource.dbcp2.max-total: 100
spring.datasource.dbcp2.min-idle: 8
spring.datasource.dbcp2.max-idle: 8
#spring.datasource.max-wait=
#spring.datasource.time-between-eviction-runs-millis=
#spring.datasource.min-evictable-idle-time-millis=
      
config:
    oauth2:
        privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIICXQIBAAKBgQDNQZKqTlO/+2b4ZdhqGJzGBDltb5PZmBz1ALN2YLvt341pH6i5
            mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE/myh1zM6m8cbL5cYFPyP099t
            hbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26hL9dSAZuA8xExjlPmQIDAQAB
            AoGAImnYGU3ApPOVtBf/TOqLfne+2SZX96eVU06myDY3zA4rO3DfbR7CzCLE6qPn
            yDAIiW0UQBs0oBDdWOnOqz5YaePZu/yrLyj6KM6Q2e9ywRDtDh3ywrSfGpjdSvvo
            aeL1WesBWsgWv1vFKKvES7ILFLUxKwyCRC2Lgh7aI9GGZfECQQD84m98Yrehhin3
            fZuRaBNIu348Ci7ZFZmrvyxAIxrV4jBjpACW0RM2BvF5oYM2gOJqIfBOVjmPwUro
            bYEFcHRvAkEAz8jsfmxsZVwh3Y/Y47BzhKIC5FLaads541jNjVWfrPirljyCy1n4
            sg3WQH2IEyap3WTP84+csCtsfNfyK7fQdwJBAJNRyobY74cupJYkW5OK4OkXKQQL
            Hp2iosJV/Y5jpQeC3JO/gARcSmfIBbbI66q9zKjtmpPYUXI4tc3PtUEY8QsCQQCc
            xySyC0sKe6bNzyC+Q8AVvkxiTKWiI5idEr8duhJd589H72Zc2wkMB+a2CEGo+Y5H
            jy5cvuph/pG/7Qw7sljnAkAy/feClt1mUEiAcWrHRwcQ71AoA0+21yC9VkqPNrn3
            w7OEg8gBqPjRlXBNb00QieNeGGSkXOoU6gFschR22Dzy
            -----END RSA PRIVATE KEY-----

        publicKey: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----
        

---

spring:
    profiles: dev

#mysql database setting
#spring.profiles.active=dev
spring.jpa.database: mysql
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost/oauthdev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: oauth
spring.datasource.password: oauth
# db init settings
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.showSql: true
spring.datasource.initialization-mode: NEVER
spring.datasource.sqlScriptEncoding: UTF-8   

---

spring:
    profiles: intg

spring.jpa.database: mysql
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost/oauthintg?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: oauth
spring.datasource.password: oauth
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.showSql: true
spring.datasource.initialization-mode: NEVER
spring.datasource.sqlScriptEncoding: UTF-8       
    
---

spring:
    profiles: uat

spring.jpa.database: mysql
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost/oauthuat?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: oauth
spring.datasource.password: oauth
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.showSql: true
spring.datasource.initialization-mode: NEVER
spring.datasource.sqlScriptEncoding: UTF-8    
   
---

spring:
    profiles: prod    

spring.jpa.database: mysql
spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost/oauthprod?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username: oauth
spring.datasource.password: oauth
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.showSql: true
spring.datasource.initialization-mode: NEVER
spring.datasource.sqlScriptEncoding: UTF-8       