server:
  port: 8843
  ssl:
    enabled: true
    keyStoreType: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password
    key-alias: tomcat
  http:
    port:
      8888

#spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#spring.cloud.config.server.git.uri: ${HOME}/config-repo

spring.data.mongodb.uri: mongodb://localhost/config-db

    

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
